### ISSUE TITLE
Zip option not actually compressing?

### ISSUE THREAD

**Issue by rux616** [fireundubh/pyro#12]
Pyro Version: 1629846756
Windows Version: 10 Pro 21H1 build 19043.1200
VSCode Version: 1.59.1
VSCode Papyrus Extension Version: 2.23.1

In my project file, I have the following:

```xml
<PapyrusProject
    ...
    Zip="true"
>
    ...
    <ZipFiles Output="@BuildPath\Release">
        <ZipFile Name="@ModName v@ModVersion" RootDir="@ModPath" Compression="deflate">
            <Include>**\@ModName.esp</Include>
            <Include Path=".">**\@ModName.ba2</Include>
            <Include>MCM\**\*.*</Include>
            <Include>Docs\**\*.*</Include>
        </ZipFile>
        <ZipFile Name="@ModName v@ModVersion - Source" RootDir="@ModPath" Compression="deflate">
            <Include>**\*.psc</Include>
            <Include>**\*.ppj</Include>
        </ZipFile>
    </ZipFiles>
</PapyrusProject>
```

When building via Pyro, the zip archives as configured above look like they just used the 'store' compression mode rather than 'deflate', as any text files in the archives, which should be able to be compressed, show the same size packed or unpacked, e.g.:

![image](https://user-images.githubusercontent.com/5643061/131196912-10c32c1b-5d39-496e-a893-90363705b5ee.png)

**Comment by fireundubh** [comment]
Fixed in 8dc3742.
