### ISSUE TITLE
Bitdefender Virus Threat?

### ISSUE THREAD

**Issue by stuartketcham** [fireundubh/pyro#15]
Version: 1656807840
File Package Version: pyro-master-1656807840.zip
Windows 10
Bitdefender Anti-Virus Free Version

I was trying to compile my Papyrus code in VS Code.  When VS Code tried to execute pyro.exe, my BitDefender fired off and quarantined it.

Here is the message from BitDefender:
The file C:\Users\stu\\.vscode\extensions\joelday.papyrus-lang-vscode-2.23.1\pyro\pyro.exe is infected with Gen:Variant.Lazy.272399 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

I had installed the Pyro package about 2 weeks ago and it was working fine until today.  Suddenly BitDefender thinks it's a virus.

I did run a complete systems scan and no further infection was found.
I tried to redownload the package from here, but the zip was immediately quarantined by BitDefender.

Previous versions: 
1651962568 - clear - no virus warning
1650882949 - clear - no virus warning

I can try to contact BitDefender, but I thought I should at least make you aware.

**Comment by fireundubh** [comment]
Belated thanks for the report. AV heuristics are terrible and create problems for developers.

See also: [Former Mozilla Engineer: Disable Your Antivirus Software, Except Microsoft's](https://www.bleepingcomputer.com/news/security/former-mozilla-engineer-disable-your-antivirus-software-except-microsofts/)
