### ISSUE TITLE
Incremental build issues

### ISSUE THREAD

**Issue by rjstone** [fireundubh/pyro#4]
Two things:

- Normally build products are stored in the build output directory. The "cache" directory doesn't make any sense to me for anything related to the build state. Everything related to the state of a build really ought to be in the build output dir where it can easily be deleted by the user.

- Also, normally incremental builds are implemented by checking the file modification time on the output file vs the input file, and only rebuilding the output file if it is newer. Is there any reason why this technique isn't used by pyro?

**Comment by fireundubh** [comment]
Resolved in latest build.
