### ISSUE TITLE
Multiple ZipFile nodes

### ISSUE THREAD

**Issue by Exit-9B** [fireundubh/pyro#6]
This tool is working great for me so far, but I've run into one hiccup with zip file creation, where only the first ZipFile node is processed. I have a project with 2 different releases (https://github.com/Exit-9B/The-Frozen-North/blob/master/TheFrozenNorth.ppj) and currently if I want to create both zip files, I have to run pyro twice and switch around the ZipFile nodes.

**Comment by fireundubh** [comment]
Multiple `ZipFile` nodes are not supported.

**Comment by fireundubh** [comment]
@Exit-9B: I've added this feature to the next build. Try it out: https://github.com/fireundubh/pyro/actions/runs/107096651

You'll need to update your project file like so:

```xml
  <ZipFiles Output="@MyProject">
    <ZipFile Name="@ModName" RootDir="@MyProject" Compression="deflate">
	  <Include>@MyProject\@ModName.esp</Include>
	  <Include NoRecurse="true">*.bsa</Include>
    </ZipFile>
    <ZipFile Name="@ModName" RootDir="@MyProject" Compression="deflate">
	  <Include>@MyProject\@ModName.esp</Include>
	  <Include NoRecurse="true">*.bsa</Include>
    </ZipFile>
  </ZipFiles>
```

**Comment by a-roy** [comment]
Tried it and it works, thanks!

**Comment by Exit-9B** [comment]
It works, thanks!
