### ISSUE TITLE
Game="tesv" not an accepted pattern in skyrimle.ppj file.

### ISSUE THREAD

**Issue by JU12000** [fireundubh/pyro#7]
Steps to Reproduce:

1. Using the Papyrus for VSCode extension, create a new mod with a script file for compiling. Generate Skyrim LE Project Files and open the SkyrimLE.code-workspace.
2. Create the default build action using VSCode, it looks like this:
```
{
    // created by vscode papyrus-lang papyrus.skyrimSpecialEdition.generateProject
    "version": "2.0.0",
    "tasks": [
        {
            "type": "pyro",
            "projectFile": "skyrimle.ppj",
            "gamePath": "S:\\skyrim\\",
            "problemMatcher": [
                "$PapyrusCompiler"
            ],
            "label": "pyro: Compile Project (skyrimle.ppj)",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
3. Ctrl+Shift+B to build the solution, with the following skyrimle.ppj file:
```
<?xml version='1.0'?><!-- Game is either sse, tesv, or fo4 -->
<PapyrusProject xmlns="PapyrusProject.xsd"
    Flags="TESV_Papyrus_Flags.flg"
    Game="tesv"
    Output="..\..\overwrite\Scripts"
    Optimize="true"
    Release="false"
    Final="false">
    <Imports>
        <Import>.\Scripts\Source</Import>
        <Import>..\SKSE Scripts\Scripts\Source</Import>
        <Import>..\PapyrusUtil\Scripts\Source</Import>
        <Import>..\SkyUI\Scripts\Source</Import>
        <Import>S:\skyrim\Data\Scripts\Source</Import>
        <Import>S:\skyrim\Data\Scripts\Source\Dawnguard</Import>
        <Import>S:\skyrim\Data\Scripts\Source\Dragonborn</Import>
        <Import>S:\skyrim\Data\Scripts\Source\Hearthfire</Import>
    </Imports>
    <Folders>
        <Folder>.\Scripts\Source</Folder>
    </Folders>
</PapyrusProject>
```

4. The following error is received:
`[ERRO] Failed to validate XML Schema.
        Element '{PapyrusProject.xsd}PapyrusProject', attribute 'Game': [facet 'pattern'] The value 'tesv' is not accepted by the pattern '[fF][oO]4'., line 8
The terminal process terminated with exit code: 1`

Confirmed that the build process runs correctly when setting Game="sse" or Game="fo4" in the above skyrimle.ppj file.

Any insight on this? A quick Google search returned nothing.

**Comment by fireundubh** [comment]
Fixed in https://github.com/fireundubh/pyro/commit/df4031cea237a6b3961640cd5452e0676feaf910.
